# Generated by Django 3.0.5 on 2021-01-15 13:17

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('users', 'User')
    for row in MyModel.objects.all():
        row.confirmation_code = uuid.uuid4()
        row.save(update_fields=['confirmation_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_uuid_field'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
